package su.terrafirmagreg.core.compat.emi;

	// This file is automatically generated by the OresToFieldGuide program in Tools-Modern.
	public class ExportedOreVeinInfo {
		public static final OreVeinInfoRecipe[] RECIPES = {
			new OreVeinInfoRecipe("deep_sheldonite", "minecraft:overworld", 
				320, 0.3, -64, 0, 30, 0, 0, new String[] {
				"tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("bornite", 53),new OreVeinInfoRecipe.WeightedBlock("cooperite", 38),new OreVeinInfoRecipe.WeightedBlock("platinum", 7),}),
			new OreVeinInfoRecipe("deep_garnet_amethyst", "minecraft:overworld", 
				230, 0.25, -64, 26, 40, 8, 0, new String[] {
				"tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("red_garnet", 5),new OreVeinInfoRecipe.WeightedBlock("yellow_garnet", 15),new OreVeinInfoRecipe.WeightedBlock("amethyst", 65),new OreVeinInfoRecipe.WeightedBlock("opal", 15),}),
			new OreVeinInfoRecipe("deep_garnet_opal", "minecraft:overworld", 
				220, 0.35, -64, 62, 26, 6, 0, new String[] {
				"tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite","tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("red_garnet", 5),new OreVeinInfoRecipe.WeightedBlock("yellow_garnet", 15),new OreVeinInfoRecipe.WeightedBlock("amethyst", 25),new OreVeinInfoRecipe.WeightedBlock("opal", 55),}),
			new OreVeinInfoRecipe("deep_gold", "minecraft:overworld", 
				260, 0.45, -64, 30, 32, 0, 0, new String[] {
				"tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite","tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("goethite", 5),new OreVeinInfoRecipe.WeightedBlock("yellow_limonite", 5),new OreVeinInfoRecipe.WeightedBlock("hematite", 15),new OreVeinInfoRecipe.WeightedBlock("gold", 75),}),
			new OreVeinInfoRecipe("deep_hematite", "minecraft:overworld", 
				220, 0.35, -64, 30, 30, 0, 0, new String[] {
				"tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("goethite", 25),new OreVeinInfoRecipe.WeightedBlock("yellow_limonite", 15),new OreVeinInfoRecipe.WeightedBlock("hematite", 35),new OreVeinInfoRecipe.WeightedBlock("gold", 5),new OreVeinInfoRecipe.WeightedBlock("ruby", 20),}),
			new OreVeinInfoRecipe("deep_limonite", "minecraft:overworld", 
				240, 0.35, -64, 30, 32, 0, 0, new String[] {
				"tfc:rock/raw/marble","tfc:rock/raw/limestone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("goethite", 50),new OreVeinInfoRecipe.WeightedBlock("yellow_limonite", 15),new OreVeinInfoRecipe.WeightedBlock("hematite", 15),new OreVeinInfoRecipe.WeightedBlock("malachite", 20),}),
			new OreVeinInfoRecipe("deep_magnetite", "minecraft:overworld", 
				225, 0.3, -64, 30, 20, 0, 0, new String[] {
				"tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("magnetite", 8),new OreVeinInfoRecipe.WeightedBlock("vanadium_magnetite", 25),new OreVeinInfoRecipe.WeightedBlock("chromite", 33),new OreVeinInfoRecipe.WeightedBlock("gold", 25),new OreVeinInfoRecipe.WeightedBlock("sapphire", 8),}),
			new OreVeinInfoRecipe("deep_molybdenum", "minecraft:overworld", 
				245, 0.45, -64, 10, 26, 0, 0, new String[] {
				"tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite","tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("wulfenite", 47),new OreVeinInfoRecipe.WeightedBlock("molybdenite", 35),new OreVeinInfoRecipe.WeightedBlock("powellite", 17),}),
			new OreVeinInfoRecipe("deep_pitchblende", "minecraft:overworld", 
				240, 0.45, -64, -20, 24, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("pitchblende", 62),new OreVeinInfoRecipe.WeightedBlock("uraninite", 25),new OreVeinInfoRecipe.WeightedBlock("wulfenite", 12),}),
			new OreVeinInfoRecipe("deep_sapphire", "minecraft:overworld", 
				180, 0.35, -64, 26, 28, 8, 0, new String[] {
				"tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("almandine", 38),new OreVeinInfoRecipe.WeightedBlock("pyrope", 27),new OreVeinInfoRecipe.WeightedBlock("sapphire", 16),new OreVeinInfoRecipe.WeightedBlock("green_sapphire", 16),}),
			new OreVeinInfoRecipe("deep_scheelite", "minecraft:overworld", 
				240, 0.35, -64, 0, 20, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("scheelite", 45),new OreVeinInfoRecipe.WeightedBlock("tungstate", 35),new OreVeinInfoRecipe.WeightedBlock("lithium", 20),}),
			new OreVeinInfoRecipe("deep_topaz", "minecraft:overworld", 
				260, 0.3, -64, 26, 28, 7, 0, new String[] {
				"tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("blue_topaz", 35),new OreVeinInfoRecipe.WeightedBlock("topaz", 25),new OreVeinInfoRecipe.WeightedBlock("chalcocite", 25),new OreVeinInfoRecipe.WeightedBlock("bornite", 15),}),
			new OreVeinInfoRecipe("normal_apatite", "minecraft:overworld", 
				220, 0.25, -32, 60, 34, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("apatite", 50),new OreVeinInfoRecipe.WeightedBlock("tricalcium_phosphate", 35),new OreVeinInfoRecipe.WeightedBlock("pyrochlore", 15),}),
			new OreVeinInfoRecipe("normal_basaltic_sands", "minecraft:overworld", 
				160, 0.3, -32, 60, 48, 9, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/basalt",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("basaltic_mineral_sand", 35),new OreVeinInfoRecipe.WeightedBlock("granitic_mineral_sand", 25),new OreVeinInfoRecipe.WeightedBlock("fullers_earth", 25),new OreVeinInfoRecipe.WeightedBlock("gypsum", 15),}),
			new OreVeinInfoRecipe("normal_beryllium", "minecraft:overworld", 
				250, 0.35, -32, 50, 0, 60, 10, new String[] {
				"tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("beryllium", 35),new OreVeinInfoRecipe.WeightedBlock("emerald", 50),new OreVeinInfoRecipe.WeightedBlock("thorium", 15),}),
			new OreVeinInfoRecipe("normal_bismuthinite", "minecraft:overworld", 
				170, 0.4, -32, 75, 40, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("bismuth", 80),new OreVeinInfoRecipe.WeightedBlock("sulfur", 9),new OreVeinInfoRecipe.WeightedBlock("lead", 11),}),
			new OreVeinInfoRecipe("normal_cassiterite", "minecraft:overworld", 
				170, 0.4, -32, 75, 40, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("cassiterite", 40),new OreVeinInfoRecipe.WeightedBlock("tin", 60),}),
			new OreVeinInfoRecipe("normal_coal", "minecraft:overworld", 
				215, 0.55, 0, 210, 60, 0, 0, new String[] {
				"tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("coal", 100),}),
			new OreVeinInfoRecipe("normal_copper", "minecraft:overworld", 
				170, 0.4, -32, 75, 40, 0, 0, new String[] {
				"tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("chalcopyrite", 20),new OreVeinInfoRecipe.WeightedBlock("hematite", 5),new OreVeinInfoRecipe.WeightedBlock("pyrite", 10),new OreVeinInfoRecipe.WeightedBlock("copper", 65),}),
			new OreVeinInfoRecipe("normal_garnet_tin", "minecraft:overworld", 
				270, 0.25, -40, 64, 40, 0, 0, new String[] {
				"tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite","tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("cassiterite_sand", 35),new OreVeinInfoRecipe.WeightedBlock("garnet_sand", 25),new OreVeinInfoRecipe.WeightedBlock("asbestos", 25),new OreVeinInfoRecipe.WeightedBlock("diatomite", 15),}),
			new OreVeinInfoRecipe("normal_garnierite", "minecraft:overworld", 
				160, 0.4, -32, 60, 40, 0, 0, new String[] {
				"tfc:rock/raw/gabbro","tfc:rock/raw/diorite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("garnierite", 30),new OreVeinInfoRecipe.WeightedBlock("nickel", 10),new OreVeinInfoRecipe.WeightedBlock("cobaltite", 20),new OreVeinInfoRecipe.WeightedBlock("pentlandite", 25),new OreVeinInfoRecipe.WeightedBlock("cobalt", 15),}),
			new OreVeinInfoRecipe("normal_gold", "minecraft:overworld", 
				170, 0.4, -32, 60, 40, 12, 0, new String[] {
				"tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite","tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("goethite", 5),new OreVeinInfoRecipe.WeightedBlock("yellow_limonite", 20),new OreVeinInfoRecipe.WeightedBlock("hematite", 20),new OreVeinInfoRecipe.WeightedBlock("gold", 55),}),
			new OreVeinInfoRecipe("normal_graphite", "minecraft:overworld", 
				80, 0.4, -64, -16, 16, 6, 0, new String[] {
				"tfc:rock/raw/gabbro","tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/quartzite","tfc:rock/raw/phyllite","tfc:rock/raw/slate","tfc:rock/raw/marble","tfc:rock/raw/dacite","tfc:rock/raw/rhyolite","tfc:rock/raw/andesite","tfc:rock/raw/basalt","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("graphite", 45),new OreVeinInfoRecipe.WeightedBlock("diamond", 25),new OreVeinInfoRecipe.WeightedBlock("coal", 30),}),
			new OreVeinInfoRecipe("normal_gypsum", "minecraft:overworld", 
				180, 0.3, -32, 60, 40, 9, 0, new String[] {
				"tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("borax", 20),new OreVeinInfoRecipe.WeightedBlock("calcite", 30),new OreVeinInfoRecipe.WeightedBlock("fullers_earth", 15),new OreVeinInfoRecipe.WeightedBlock("gypsum", 35),}),
			new OreVeinInfoRecipe("normal_hematite", "minecraft:overworld", 
				210, 0.4, -32, 75, 40, 0, 0, new String[] {
				"tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("goethite", 15),new OreVeinInfoRecipe.WeightedBlock("yellow_limonite", 30),new OreVeinInfoRecipe.WeightedBlock("hematite", 50),new OreVeinInfoRecipe.WeightedBlock("gold", 5),}),
			new OreVeinInfoRecipe("normal_lapis", "minecraft:overworld", 
				170, 0.25, -60, 10, 40, 0, 0, new String[] {
				"tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("lazurite", 35),new OreVeinInfoRecipe.WeightedBlock("sodalite", 25),new OreVeinInfoRecipe.WeightedBlock("lapis", 25),new OreVeinInfoRecipe.WeightedBlock("calcite", 15),}),
			new OreVeinInfoRecipe("normal_limonite", "minecraft:overworld", 
				190, 0.4, -32, 75, 40, 0, 0, new String[] {
				"tfc:rock/raw/marble","tfc:rock/raw/limestone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("goethite", 15),new OreVeinInfoRecipe.WeightedBlock("yellow_limonite", 50),new OreVeinInfoRecipe.WeightedBlock("hematite", 20),new OreVeinInfoRecipe.WeightedBlock("malachite", 15),}),
			new OreVeinInfoRecipe("normal_lubricant", "minecraft:overworld", 
				190, 0.25, -40, 56, 36, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("soapstone", 30),new OreVeinInfoRecipe.WeightedBlock("talc", 20),new OreVeinInfoRecipe.WeightedBlock("glauconite_sand", 25),new OreVeinInfoRecipe.WeightedBlock("pentlandite", 15),new OreVeinInfoRecipe.WeightedBlock("trona", 10),}),
			new OreVeinInfoRecipe("normal_magnetite", "minecraft:overworld", 
				200, 0.3, -32, 75, 30, 0, 0, new String[] {
				"tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("magnetite", 63),new OreVeinInfoRecipe.WeightedBlock("vanadium_magnetite", 22),new OreVeinInfoRecipe.WeightedBlock("gold", 9),new OreVeinInfoRecipe.WeightedBlock("chromite", 4),}),
			new OreVeinInfoRecipe("normal_manganese", "minecraft:overworld", 
				195, 0.3, -32, 60, 30, 0, 0, new String[] {
				"tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("grossular", 37),new OreVeinInfoRecipe.WeightedBlock("spessartine", 25),new OreVeinInfoRecipe.WeightedBlock("pyrolusite", 25),new OreVeinInfoRecipe.WeightedBlock("tantalite", 12),}),
			new OreVeinInfoRecipe("normal_mica", "minecraft:overworld", 
				190, 0.25, 0, 210, 36, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("kyanite", 35),new OreVeinInfoRecipe.WeightedBlock("mica", 25),new OreVeinInfoRecipe.WeightedBlock("bauxite", 25),new OreVeinInfoRecipe.WeightedBlock("pollucite", 15),}),
			new OreVeinInfoRecipe("normal_monazite", "minecraft:overworld", 
				205, 0.25, -32, 50, 35, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("bastnasite", 62),new OreVeinInfoRecipe.WeightedBlock("monazite", 31),new OreVeinInfoRecipe.WeightedBlock("neodymium", 6),}),
			new OreVeinInfoRecipe("normal_oilsands", "minecraft:overworld", 
				185, 0.2, 0, 70, 55, 0, 0, new String[] {
				"tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("oilsands", 100),}),
			new OreVeinInfoRecipe("normal_olivine", "minecraft:overworld", 
				180, 0.25, -40, 30, 26, 0, 0, new String[] {
				"tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite","tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("bentonite", 35),new OreVeinInfoRecipe.WeightedBlock("magnesite", 25),new OreVeinInfoRecipe.WeightedBlock("olivine", 25),new OreVeinInfoRecipe.WeightedBlock("glauconite_sand", 15),}),
			new OreVeinInfoRecipe("normal_quartz", "minecraft:overworld", 
				190, 0.3, -32, 100, 40, 0, 0, new String[] {
				"tfc:rock/raw/shale","tfc:rock/raw/quartzite","tfc:rock/raw/schist","tfc:rock/raw/gneiss",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("quartzite", 43),new OreVeinInfoRecipe.WeightedBlock("barite", 37),new OreVeinInfoRecipe.WeightedBlock("asbestos", 18),}),
			new OreVeinInfoRecipe("normal_redstone", "minecraft:overworld", 
				160, 0.4, -32, 100, 40, 0, 0, new String[] {
				"tfc:rock/raw/granite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("redstone", 45),new OreVeinInfoRecipe.WeightedBlock("ruby", 35),new OreVeinInfoRecipe.WeightedBlock("cinnabar", 20),}),
			new OreVeinInfoRecipe("normal_salt", "minecraft:overworld", 
				175, 0.4, 30, 70, 40, 4, 0, new String[] {
				"tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("rock_salt", 40),new OreVeinInfoRecipe.WeightedBlock("salt", 30),new OreVeinInfoRecipe.WeightedBlock("lepidolite", 15),new OreVeinInfoRecipe.WeightedBlock("borax", 15),}),
			new OreVeinInfoRecipe("normal_saltpeter", "minecraft:overworld", 
				210, 0.3, -32, 60, 40, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("saltpeter", 35),new OreVeinInfoRecipe.WeightedBlock("diatomite", 25),new OreVeinInfoRecipe.WeightedBlock("electrotine", 25),new OreVeinInfoRecipe.WeightedBlock("alunite", 15),}),
			new OreVeinInfoRecipe("normal_silver", "minecraft:overworld", 
				160, 0.4, -32, 75, 40, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/gneiss",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("galena", 30),new OreVeinInfoRecipe.WeightedBlock("silver", 15),new OreVeinInfoRecipe.WeightedBlock("lead", 55),}),
			new OreVeinInfoRecipe("normal_sphalerite", "minecraft:overworld", 
				170, 0.4, -32, 75, 40, 0, 0, new String[] {
				"tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite","tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("sulfur", 35),new OreVeinInfoRecipe.WeightedBlock("sphalerite", 40),new OreVeinInfoRecipe.WeightedBlock("pyrite", 25),}),
			new OreVeinInfoRecipe("normal_spodumene", "minecraft:overworld", 
				180, 0.375, 20, 60, 35, 6, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("rock_salt", 20),new OreVeinInfoRecipe.WeightedBlock("salt", 30),new OreVeinInfoRecipe.WeightedBlock("lepidolite", 15),new OreVeinInfoRecipe.WeightedBlock("spodumene", 35),}),
			new OreVeinInfoRecipe("normal_sulfur", "minecraft:overworld", 
				165, 0.2, 0, 210, 45, 0, 0, new String[] {
				"tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("sulfur", 50),new OreVeinInfoRecipe.WeightedBlock("pyrite", 35),new OreVeinInfoRecipe.WeightedBlock("sphalerite", 15),}),
			new OreVeinInfoRecipe("normal_tetrahedrite", "minecraft:overworld", 
				170, 0.4, -32, 75, 40, 0, 0, new String[] {
				"tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("tetrahedrite", 50),new OreVeinInfoRecipe.WeightedBlock("copper", 30),new OreVeinInfoRecipe.WeightedBlock("stibnite", 20),}),
			new OreVeinInfoRecipe("surface_bismuthinite", "minecraft:overworld", 
				140, 0.25, 60, 210, 50, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("bismuth", 85),new OreVeinInfoRecipe.WeightedBlock("sulfur", 3),new OreVeinInfoRecipe.WeightedBlock("lead", 7),new OreVeinInfoRecipe.WeightedBlock("silver", 5),}),
			new OreVeinInfoRecipe("surface_cassiterite", "minecraft:overworld", 
				135, 0.25, 60, 210, 50, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("cassiterite", 60),new OreVeinInfoRecipe.WeightedBlock("tin", 40),}),
			new OreVeinInfoRecipe("surface_copper", "minecraft:overworld", 
				200, 0.25, 20, 217, 50, 0, 0, new String[] {
				"tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("chalcopyrite", 61),new OreVeinInfoRecipe.WeightedBlock("zeolite", 16),new OreVeinInfoRecipe.WeightedBlock("cassiterite", 5),new OreVeinInfoRecipe.WeightedBlock("realgar", 16),}),
			new OreVeinInfoRecipe("surface_sphalerite", "minecraft:overworld", 
				145, 0.25, 60, 210, 50, 0, 0, new String[] {
				"tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite","tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("sulfur", 55),new OreVeinInfoRecipe.WeightedBlock("sphalerite", 40),new OreVeinInfoRecipe.WeightedBlock("pyrite", 5),}),
			new OreVeinInfoRecipe("surface_tetrahedrite", "minecraft:overworld", 
				140, 0.25, 60, 210, 50, 0, 0, new String[] {
				"tfc:rock/raw/quartzite","tfc:rock/raw/slate","tfc:rock/raw/phyllite","tfc:rock/raw/schist","tfc:rock/raw/gneiss","tfc:rock/raw/marble",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("tetrahedrite", 60),new OreVeinInfoRecipe.WeightedBlock("copper", 20),new OreVeinInfoRecipe.WeightedBlock("stibnite", 20),}),
			new OreVeinInfoRecipe("deep_mars_chromite", "ad_astra:mars", 
				370, 0.3, -20, 0, 60, 0, 0, new String[] {
				"ad_astra:mars_stone","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/chert","tfc:rock/raw/chalk","tfc:rock/raw/basalt","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("redstone", 45),new OreVeinInfoRecipe.WeightedBlock("ruby", 35),new OreVeinInfoRecipe.WeightedBlock("chromite", 20),}),
			new OreVeinInfoRecipe("deep_mars_pitchblende", "ad_astra:mars", 
				370, 0.3, -20, 0, 60, 0, 0, new String[] {
				"ad_astra:mars_stone","ad_astra:venus_stone","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("pitchblende", 52),new OreVeinInfoRecipe.WeightedBlock("thorium", 26),new OreVeinInfoRecipe.WeightedBlock("uraninite", 21),}),
			new OreVeinInfoRecipe("deep_mars_sheldonite", "ad_astra:mars", 
				370, 0.3, -20, 0, 60, 0, 0, new String[] {
				"ad_astra:mars_stone","ad_astra:venus_stone","gtceu:red_granite","tfc:rock/raw/diorite","tfc:rock/raw/conglomerate","tfc:rock/raw/chert","tfc:rock/raw/chalk","tfc:rock/raw/basalt","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("bornite", 35),new OreVeinInfoRecipe.WeightedBlock("cooperite", 25),new OreVeinInfoRecipe.WeightedBlock("nickel", 25),new OreVeinInfoRecipe.WeightedBlock("platinum", 15),}),
			new OreVeinInfoRecipe("mars_almandine", "ad_astra:mars", 
				280, 0.35, 0, 70, 65, 8, 0, new String[] {
				"ad_astra:mars_stone","ad_astra:venus_stone","gtceu:red_granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/dolomite","tfc:rock/raw/chert",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("almandine", 36),new OreVeinInfoRecipe.WeightedBlock("pyrope", 26),new OreVeinInfoRecipe.WeightedBlock("sapphire", 15),new OreVeinInfoRecipe.WeightedBlock("green_sapphire", 15),new OreVeinInfoRecipe.WeightedBlock("hematite", 5),}),
			new OreVeinInfoRecipe("mars_apatite", "ad_astra:mars", 
				220, 0.25, 0, 70, 45, 0, 0, new String[] {
				"ad_astra:venus_stone","gtceu:red_granite","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/chert","tfc:rock/raw/chalk","tfc:rock/raw/basalt","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("apatite", 47),new OreVeinInfoRecipe.WeightedBlock("tricalcium_phosphate", 33),new OreVeinInfoRecipe.WeightedBlock("pyrochlore", 14),new OreVeinInfoRecipe.WeightedBlock("hematite", 4),}),
			new OreVeinInfoRecipe("mars_beryllium", "ad_astra:mars", 
				350, 0.35, -20, 50, 0, 40, 8, new String[] {
				"tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("beryllium", 35),new OreVeinInfoRecipe.WeightedBlock("emerald", 50),new OreVeinInfoRecipe.WeightedBlock("realgar", 15),}),
			new OreVeinInfoRecipe("mars_coal", "ad_astra:mars", 
				215, 0.6, 0, 70, 55, 0, 0, new String[] {
				"ad_astra:mars_stone","ad_astra:venus_stone","gtceu:red_granite","tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/claystone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chalk","tfc:rock/raw/basalt","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("coal", 70),new OreVeinInfoRecipe.WeightedBlock("hematite", 30),}),
			new OreVeinInfoRecipe("mars_copper", "ad_astra:mars", 
				220, 0.4, 0, 70, 50, 0, 0, new String[] {
				"ad_astra:mars_stone","ad_astra:venus_stone","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/basalt","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("chalcopyrite", 65),new OreVeinInfoRecipe.WeightedBlock("copper", 20),new OreVeinInfoRecipe.WeightedBlock("pyrite", 10),new OreVeinInfoRecipe.WeightedBlock("hematite", 5),}),
			new OreVeinInfoRecipe("mars_galena", "ad_astra:mars", 
				215, 0.4, 0, 70, 50, 0, 0, new String[] {
				"ad_astra:mars_stone","gtceu:red_granite","tfc:rock/raw/granite","tfc:rock/raw/gabbro","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/chert","tfc:rock/raw/chalk","tfc:rock/raw/basalt","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("galena", 40),new OreVeinInfoRecipe.WeightedBlock("silver", 20),new OreVeinInfoRecipe.WeightedBlock("lead", 33),new OreVeinInfoRecipe.WeightedBlock("hematite", 6),}),
			new OreVeinInfoRecipe("mars_sapphire", "ad_astra:mars", 
				230, 0.4, 0, 70, 40, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/chert","tfc:rock/raw/chalk",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("green_sapphire", 5),new OreVeinInfoRecipe.WeightedBlock("bauxite", 20),new OreVeinInfoRecipe.WeightedBlock("electrotine", 20),new OreVeinInfoRecipe.WeightedBlock("gold", 55),}),
			new OreVeinInfoRecipe("mars_hematite", "ad_astra:mars", 
				210, 0.4, 0, 70, 40, 0, 0, new String[] {
				"ad_astra:mars_stone","gtceu:red_granite","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/basalt","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("hematite", 50),new OreVeinInfoRecipe.WeightedBlock("yellow_limonite", 30),new OreVeinInfoRecipe.WeightedBlock("goethite", 15),new OreVeinInfoRecipe.WeightedBlock("gold", 5),}),
			new OreVeinInfoRecipe("mars_lubricant", "ad_astra:mars", 
				220, 0.25, 0, 70, 40, 0, 0, new String[] {
				"ad_astra:mars_stone","gtceu:red_granite","tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("soapstone", 14),new OreVeinInfoRecipe.WeightedBlock("talc", 28),new OreVeinInfoRecipe.WeightedBlock("glauconite_sand", 21),new OreVeinInfoRecipe.WeightedBlock("trona", 21),new OreVeinInfoRecipe.WeightedBlock("pentlandite", 7),new OreVeinInfoRecipe.WeightedBlock("hematite", 7),}),
			new OreVeinInfoRecipe("mars_neodynium", "ad_astra:mars", 
				215, 0.4, 0, 70, 45, 0, 0, new String[] {
				"ad_astra:mars_stone","ad_astra:venus_stone","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","tfc:rock/raw/basalt",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("bastnasite", 58),new OreVeinInfoRecipe.WeightedBlock("monazite", 29),new OreVeinInfoRecipe.WeightedBlock("neodymium", 5),new OreVeinInfoRecipe.WeightedBlock("hematite", 5),}),
			new OreVeinInfoRecipe("mars_nickel", "ad_astra:mars", 
				250, 0.4, 0, 70, 55, 0, 0, new String[] {
				"ad_astra:mars_stone","gtceu:red_granite","tfc:rock/raw/granite","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/chalk","tfc:rock/raw/basalt","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("garnierite", 35),new OreVeinInfoRecipe.WeightedBlock("nickel", 28),new OreVeinInfoRecipe.WeightedBlock("cobaltite", 28),new OreVeinInfoRecipe.WeightedBlock("hematite", 7),}),
			new OreVeinInfoRecipe("mars_pitchblende", "ad_astra:mars", 
				220, 0.55, 0, 70, 20, 0, 0, new String[] {
				"ad_astra:mars_stone","ad_astra:venus_stone","gtceu:red_granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/shale","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("pitchblende", 41),new OreVeinInfoRecipe.WeightedBlock("thorium", 29),new OreVeinInfoRecipe.WeightedBlock("hematite", 29),}),
			new OreVeinInfoRecipe("mars_quartzite", "ad_astra:mars", 
				210, 0.3, 0, 70, 40, 0, 0, new String[] {
				"ad_astra:mars_stone","ad_astra:venus_stone","gtceu:red_granite","tfc:rock/raw/granite","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/chert","tfc:rock/raw/chalk",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("quartzite", 41),new OreVeinInfoRecipe.WeightedBlock("barite", 35),new OreVeinInfoRecipe.WeightedBlock("asbestos", 17),new OreVeinInfoRecipe.WeightedBlock("hematite", 5),}),
			new OreVeinInfoRecipe("mars_salt", "ad_astra:mars", 
				210, 0.4, 0, 70, 40, 6, 0, new String[] {
				"ad_astra:mars_stone","ad_astra:venus_stone","gtceu:red_granite","tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/chert","tfc:rock/raw/chalk",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("rock_salt", 20),new OreVeinInfoRecipe.WeightedBlock("salt", 30),new OreVeinInfoRecipe.WeightedBlock("lepidolite", 15),new OreVeinInfoRecipe.WeightedBlock("spodumene", 35),}),
			new OreVeinInfoRecipe("mars_stibnite", "ad_astra:mars", 
				210, 0.4, 0, 70, 40, 0, 0, new String[] {
				"ad_astra:mars_stone","ad_astra:venus_stone","gtceu:red_granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/shale","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","tfc:rock/raw/basalt","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("tetrahedrite", 47),new OreVeinInfoRecipe.WeightedBlock("copper", 28),new OreVeinInfoRecipe.WeightedBlock("stibnite", 19),new OreVeinInfoRecipe.WeightedBlock("hematite", 4),}),
			new OreVeinInfoRecipe("mars_sulfur", "ad_astra:mars", 
				215, 0.2, 0, 70, 45, 0, 0, new String[] {
				"ad_astra:mars_stone","ad_astra:venus_stone","tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/chert","tfc:rock/raw/chalk","tfc:rock/raw/basalt","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("sulfur", 14),new OreVeinInfoRecipe.WeightedBlock("pyrite", 42),new OreVeinInfoRecipe.WeightedBlock("sphalerite", 23),new OreVeinInfoRecipe.WeightedBlock("hematite", 19),}),
			new OreVeinInfoRecipe("mars_tantalite", "ad_astra:mars", 
				230, 0.3, 0, 70, 42, 0, 0, new String[] {
				"ad_astra:mars_stone","ad_astra:venus_stone","gtceu:red_granite","tfc:rock/raw/gabbro","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/chert","tfc:rock/raw/chalk","tfc:rock/raw/basalt",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("grossular", 37),new OreVeinInfoRecipe.WeightedBlock("spessartine", 25),new OreVeinInfoRecipe.WeightedBlock("pyrolusite", 25),new OreVeinInfoRecipe.WeightedBlock("tantalite", 12),}),
			new OreVeinInfoRecipe("mars_tungsten", "ad_astra:mars", 
				280, 0.45, 0, 70, 50, 0, 0, new String[] {
				"gtceu:red_granite","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","tfc:rock/raw/basalt",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("scheelite", 42),new OreVeinInfoRecipe.WeightedBlock("tungstate", 33),new OreVeinInfoRecipe.WeightedBlock("lithium", 19),new OreVeinInfoRecipe.WeightedBlock("hematite", 4),}),
			new OreVeinInfoRecipe("mars_surface_bismuthinite", "ad_astra:mars", 
				140, 0.25, 80, 180, 45, 0, 0, new String[] {
				"ad_astra:mars_stone","ad_astra:venus_stone","gtceu:red_granite","tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","tfc:rock/raw/basalt","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("bismuth", 40),new OreVeinInfoRecipe.WeightedBlock("hematite", 20),new OreVeinInfoRecipe.WeightedBlock("sulfur", 20),new OreVeinInfoRecipe.WeightedBlock("gypsum", 20),}),
			new OreVeinInfoRecipe("mars_surface_cassiterite", "ad_astra:mars", 
				135, 0.25, 80, 180, 45, 0, 0, new String[] {
				"ad_astra:mars_stone","ad_astra:venus_stone","gtceu:red_granite","tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","tfc:rock/raw/basalt","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("cassiterite", 55),new OreVeinInfoRecipe.WeightedBlock("tin", 35),new OreVeinInfoRecipe.WeightedBlock("saltpeter", 10),}),
			new OreVeinInfoRecipe("mars_surface_hematite", "ad_astra:mars", 
				140, 0.25, 80, 180, 45, 0, 0, new String[] {
				"ad_astra:mars_stone","ad_astra:venus_stone","gtceu:red_granite","tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","tfc:rock/raw/basalt","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("hematite", 55),new OreVeinInfoRecipe.WeightedBlock("yellow_limonite", 33),new OreVeinInfoRecipe.WeightedBlock("gold", 5),new OreVeinInfoRecipe.WeightedBlock("calcite", 5),}),
			new OreVeinInfoRecipe("mars_surface_nickel_galena", "ad_astra:mars", 
				150, 0.25, 80, 180, 45, 0, 0, new String[] {
				"ad_astra:mars_stone","ad_astra:venus_stone","gtceu:red_granite","tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","tfc:rock/raw/basalt","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("sphalerite", 17),new OreVeinInfoRecipe.WeightedBlock("nickel", 23),new OreVeinInfoRecipe.WeightedBlock("galena", 35),new OreVeinInfoRecipe.WeightedBlock("silver", 11),new OreVeinInfoRecipe.WeightedBlock("cobaltite", 11),}),
			new OreVeinInfoRecipe("mars_surface_tetrahedrite", "ad_astra:mars", 
				140, 0.25, 80, 180, 45, 0, 0, new String[] {
				"ad_astra:mars_stone","ad_astra:venus_stone","gtceu:red_granite","tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/shale","tfc:rock/raw/claystone","tfc:rock/raw/limestone","tfc:rock/raw/conglomerate","tfc:rock/raw/dolomite","tfc:rock/raw/chert","tfc:rock/raw/chalk","tfc:rock/raw/basalt","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("tetrahedrite", 57),new OreVeinInfoRecipe.WeightedBlock("copper", 19),new OreVeinInfoRecipe.WeightedBlock("stibnite", 19),new OreVeinInfoRecipe.WeightedBlock("redstone", 4),}),
			new OreVeinInfoRecipe("moon_apatite", "ad_astra:moon", 
				250, 0.3, 0, 100, 35, 0, 0, new String[] {
				"tfc:rock/raw/diorite","ad_astra:moon_stone","ad_astra:moon_deepslate",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("apatite", 23),new OreVeinInfoRecipe.WeightedBlock("tricalcium_phosphate", 33),new OreVeinInfoRecipe.WeightedBlock("pyrochlore", 38),new OreVeinInfoRecipe.WeightedBlock("olivine", 4),}),
			new OreVeinInfoRecipe("moon_bauxite", "ad_astra:moon", 
				200, 0.35, 0, 80, 40, 0, 0, new String[] {
				"tfc:rock/raw/basalt","ad_astra:moon_stone","ad_astra:moon_deepslate","ad_astra:glacio_stone","tfc:rock/raw/diorite","tfc:rock/raw/rhyolite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("bauxite", 36),new OreVeinInfoRecipe.WeightedBlock("ilmenite", 42),new OreVeinInfoRecipe.WeightedBlock("armalcolite", 21),}),
			new OreVeinInfoRecipe("moon_beryllium", "ad_astra:moon", 
				260, 0.35, 0, 120, 0, 70, 8, new String[] {
				"tfc:rock/raw/basalt","ad_astra:moon_stone","ad_astra:glacio_stone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("beryllium", 31),new OreVeinInfoRecipe.WeightedBlock("emerald", 45),new OreVeinInfoRecipe.WeightedBlock("thorium", 0),new OreVeinInfoRecipe.WeightedBlock("olivine", 4),new OreVeinInfoRecipe.WeightedBlock("rock_salt", 18),}),
			new OreVeinInfoRecipe("moon_cassiterite", "ad_astra:moon", 
				210, 0.3, 10, 128, 35, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","ad_astra:moon_deepslate",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("chalcopyrite", 35),new OreVeinInfoRecipe.WeightedBlock("zeolite", 5),new OreVeinInfoRecipe.WeightedBlock("cassiterite", 41),new OreVeinInfoRecipe.WeightedBlock("tin", 17),}),
			new OreVeinInfoRecipe("moon_sheldonite", "ad_astra:moon", 
				260, 0.3, 0, 70, 30, 0, 0, new String[] {
				"tfc:rock/raw/basalt","tfc:rock/raw/andesite","ad_astra:glacio_stone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("bornite", 35),new OreVeinInfoRecipe.WeightedBlock("cooperite", 25),new OreVeinInfoRecipe.WeightedBlock("platinum", 15),new OreVeinInfoRecipe.WeightedBlock("nickel", 25),}),
			new OreVeinInfoRecipe("moon_desh", "ad_astra:moon", 
				230, 0.35, 10, 80, 30, 0, 0, new String[] {
				"tfc:rock/raw/andesite","tfc:rock/raw/dacite","tfc:rock/raw/gabbro","tfc:rock/raw/basalt",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("desh", 25),new OreVeinInfoRecipe.WeightedBlock("ilmenite", 30),new OreVeinInfoRecipe.WeightedBlock("aluminium", 25),new OreVeinInfoRecipe.WeightedBlock("armalcolite", 20),}),
			new OreVeinInfoRecipe("moon_garnet", "ad_astra:moon", 
				230, 0.35, 10, 128, 35, 7, 0, new String[] {
				"tfc:rock/raw/rhyolite","tfc:rock/raw/basalt","tfc:rock/raw/andesite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("red_garnet", 9),new OreVeinInfoRecipe.WeightedBlock("yellow_garnet", 14),new OreVeinInfoRecipe.WeightedBlock("amethyst", 38),new OreVeinInfoRecipe.WeightedBlock("opal", 38),}),
			new OreVeinInfoRecipe("moon_garnierite", "ad_astra:moon", 
				250, 0.35, 5, 85, 45, 0, 0, new String[] {
				"tfc:rock/raw/gabbro","tfc:rock/raw/diorite","tfc:rock/raw/rhyolite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("garnierite", 23),new OreVeinInfoRecipe.WeightedBlock("nickel", 19),new OreVeinInfoRecipe.WeightedBlock("cobaltite", 19),new OreVeinInfoRecipe.WeightedBlock("pentlandite", 23),new OreVeinInfoRecipe.WeightedBlock("cobalt", 14),}),
			new OreVeinInfoRecipe("moon_gold", "ad_astra:moon", 
				170, 0.35, 10, 80, 35, 10, 0, new String[] {
				"tfc:rock/raw/basalt","tfc:rock/raw/granite","tfc:rock/raw/diorite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("green_sapphire", 5),new OreVeinInfoRecipe.WeightedBlock("bauxite", 20),new OreVeinInfoRecipe.WeightedBlock("magnetite", 20),new OreVeinInfoRecipe.WeightedBlock("gold", 55),}),
			new OreVeinInfoRecipe("moon_graphite", "ad_astra:moon", 
				260, 0.4, 0, 120, 0, 60, 9, new String[] {
				"tfc:rock/raw/basalt","ad_astra:moon_stone","ad_astra:glacio_stone","tfc:rock/raw/gabbro","tfc:rock/raw/basalt",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("graphite", 52),new OreVeinInfoRecipe.WeightedBlock("diamond", 36),new OreVeinInfoRecipe.WeightedBlock("olivine", 10),}),
			new OreVeinInfoRecipe("moon_gypsum", "ad_astra:moon", 
				180, 0.3, 10, 100, 30, 9, 0, new String[] {
				"ad_astra:moon_stone","ad_astra:glacio_stone","ad_astra:moon_deepslate",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("borax", 20),new OreVeinInfoRecipe.WeightedBlock("calcite", 25),new OreVeinInfoRecipe.WeightedBlock("alunite", 15),new OreVeinInfoRecipe.WeightedBlock("gypsum", 35),new OreVeinInfoRecipe.WeightedBlock("olivine", 5),}),
			new OreVeinInfoRecipe("moon_lubricant", "ad_astra:moon", 
				190, 0.25, 0, 66, 30, 0, 0, new String[] {
				"tfc:rock/raw/diorite","tfc:rock/raw/gabbro","ad_astra:moon_stone","ad_astra:moon_deepslate","tfc:rock/raw/basalt",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("soapstone", 30),new OreVeinInfoRecipe.WeightedBlock("talc", 20),new OreVeinInfoRecipe.WeightedBlock("glauconite_sand", 25),new OreVeinInfoRecipe.WeightedBlock("pentlandite", 15),new OreVeinInfoRecipe.WeightedBlock("trona", 10),}),
			new OreVeinInfoRecipe("moon_magnetite", "ad_astra:moon", 
				280, 0.25, 0, 90, 50, 0, 0, new String[] {
				"tfc:rock/raw/diorite","tfc:rock/raw/gabbro","ad_astra:moon_stone","ad_astra:moon_deepslate",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("magnetite", 25),new OreVeinInfoRecipe.WeightedBlock("vanadium_magnetite", 15),new OreVeinInfoRecipe.WeightedBlock("chromite", 40),new OreVeinInfoRecipe.WeightedBlock("gold", 15),new OreVeinInfoRecipe.WeightedBlock("sapphire", 5),}),
			new OreVeinInfoRecipe("moon_manganese", "ad_astra:moon", 
				215, 0.35, 5, 80, 30, 0, 0, new String[] {
				"tfc:rock/raw/andesite","tfc:rock/raw/basalt","tfc:rock/raw/gabbro","tfc:rock/raw/dacite","tfc:rock/raw/basalt","ad_astra:moon_deepslate",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("grossular", 37),new OreVeinInfoRecipe.WeightedBlock("spessartine", 25),new OreVeinInfoRecipe.WeightedBlock("pyrolusite", 25),new OreVeinInfoRecipe.WeightedBlock("tantalite", 12),}),
			new OreVeinInfoRecipe("moon_mica", "ad_astra:moon", 
				250, 0.25, 0, 120, 35, 0, 0, new String[] {
				"tfc:rock/raw/diorite","tfc:rock/raw/gabbro","ad_astra:moon_stone","ad_astra:moon_deepslate",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("kyanite", 33),new OreVeinInfoRecipe.WeightedBlock("mica", 23),new OreVeinInfoRecipe.WeightedBlock("bauxite", 23),new OreVeinInfoRecipe.WeightedBlock("aluminium", 14),new OreVeinInfoRecipe.WeightedBlock("olivine", 4),}),
			new OreVeinInfoRecipe("moon_molybdenum", "ad_astra:moon", 
				245, 0.35, 0, 50, 35, 0, 0, new String[] {
				"tfc:rock/raw/basalt","tfc:rock/raw/dacite","tfc:rock/raw/gabbro","ad_astra:moon_deepslate",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("wulfenite", 44),new OreVeinInfoRecipe.WeightedBlock("molybdenite", 33),new OreVeinInfoRecipe.WeightedBlock("powellite", 16),new OreVeinInfoRecipe.WeightedBlock("olivine", 5),}),
			new OreVeinInfoRecipe("moon_monazite", "ad_astra:moon", 
				310, 0.2, 0, 70, 40, 0, 0, new String[] {
				"ad_astra:glacio_stone","tfc:rock/raw/andesite","tfc:rock/raw/dacite","tfc:rock/raw/rhyolite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("bastnasite", 61),new OreVeinInfoRecipe.WeightedBlock("monazite", 30),new OreVeinInfoRecipe.WeightedBlock("neodymium", 6),new OreVeinInfoRecipe.WeightedBlock("olivine", 1),}),
			new OreVeinInfoRecipe("moon_pyrolusite", "ad_astra:moon", 
				210, 0.25, 20, 80, 35, 0, 0, new String[] {
				"tfc:rock/raw/andesite","tfc:rock/raw/basalt","tfc:rock/raw/gabbro","ad_astra:moon_stone","ad_astra:moon_deepslate",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("pyrolusite", 38),new OreVeinInfoRecipe.WeightedBlock("cobaltite", 23),new OreVeinInfoRecipe.WeightedBlock("cobalt", 23),new OreVeinInfoRecipe.WeightedBlock("tantalite", 14),}),
			new OreVeinInfoRecipe("moon_quartz", "ad_astra:moon", 
				230, 0.3, 10, 100, 45, 0, 0, new String[] {
				"tfc:rock/raw/basalt","ad_astra:moon_deepslate","tfc:rock/raw/gabbro","ad_astra:moon_stone","tfc:rock/raw/diorite","ad_astra:glacio_stone","tfc:rock/raw/dacite","tfc:rock/raw/rhyolite","tfc:rock/raw/andesite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("quartzite", 20),new OreVeinInfoRecipe.WeightedBlock("certus_quartz", 45),new OreVeinInfoRecipe.WeightedBlock("nether_quartz", 30),new OreVeinInfoRecipe.WeightedBlock("barite", 5),}),
			new OreVeinInfoRecipe("moon_redstone", "ad_astra:moon", 
				250, 0.2, 20, 100, 35, 0, 0, new String[] {
				"tfc:rock/raw/dacite","ad_astra:glacio_stone","tfc:rock/raw/andesite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("redstone", 42),new OreVeinInfoRecipe.WeightedBlock("ruby", 33),new OreVeinInfoRecipe.WeightedBlock("cinnabar", 19),new OreVeinInfoRecipe.WeightedBlock("olivine", 4),}),
			new OreVeinInfoRecipe("moon_saltpeter", "ad_astra:moon", 
				210, 0.3, 0, 90, 30, 0, 0, new String[] {
				"tfc:rock/raw/rhyolite","tfc:rock/raw/andesite","ad_astra:moon_deepslate","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("saltpeter", 29),new OreVeinInfoRecipe.WeightedBlock("soapstone", 20),new OreVeinInfoRecipe.WeightedBlock("electrotine", 37),new OreVeinInfoRecipe.WeightedBlock("talc", 12),}),
			new OreVeinInfoRecipe("moon_sapphire", "ad_astra:moon", 
				280, 0.35, 0, 100, 28, 8, 0, new String[] {
				"tfc:rock/raw/basalt","ad_astra:moon_deepslate",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("almandine", 38),new OreVeinInfoRecipe.WeightedBlock("pyrope", 27),new OreVeinInfoRecipe.WeightedBlock("sapphire", 16),new OreVeinInfoRecipe.WeightedBlock("green_sapphire", 16),new OreVeinInfoRecipe.WeightedBlock("olivine", 2),}),
			new OreVeinInfoRecipe("moon_scheelite", "ad_astra:moon", 
				200, 0.4, 0, 70, 20, 0, 0, new String[] {
				"tfc:rock/raw/rhyolite","ad_astra:glacio_stone","tfc:rock/raw/gabbro",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("scheelite", 40),new OreVeinInfoRecipe.WeightedBlock("tungstate", 50),new OreVeinInfoRecipe.WeightedBlock("lithium", 10),}),
			new OreVeinInfoRecipe("moon_silver", "ad_astra:moon", 
				210, 0.35, 20, 75, 30, 0, 0, new String[] {
				"ad_astra:moon_stone","ad_astra:moon_deepslate","tfc:rock/raw/rhyolite","tfc:rock/raw/diorite","tfc:rock/raw/dacite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("galena", 28),new OreVeinInfoRecipe.WeightedBlock("silver", 42),new OreVeinInfoRecipe.WeightedBlock("lead", 23),new OreVeinInfoRecipe.WeightedBlock("olivine", 4),}),
			new OreVeinInfoRecipe("moon_sphalerite", "ad_astra:moon", 
				205, 0.35, 2, 75, 35, 0, 0, new String[] {
				"tfc:rock/raw/basalt","tfc:rock/raw/andesite","tfc:rock/raw/gabbro","tfc:rock/raw/dacite","ad_astra:glacio_stone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("desh", 10),new OreVeinInfoRecipe.WeightedBlock("sphalerite", 50),new OreVeinInfoRecipe.WeightedBlock("pyrite", 40),}),
			new OreVeinInfoRecipe("moon_tetrahedrite", "ad_astra:moon", 
				190, 0.3, 50, 128, 35, 0, 0, new String[] {
				"tfc:rock/raw/dacite","ad_astra:glacio_stone","tfc:rock/raw/andesite","tfc:rock/raw/rhyolite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("tetrahedrite", 40),new OreVeinInfoRecipe.WeightedBlock("copper", 15),new OreVeinInfoRecipe.WeightedBlock("stibnite", 20),new OreVeinInfoRecipe.WeightedBlock("chalcocite", 25),}),
			new OreVeinInfoRecipe("moon_topaz", "ad_astra:moon", 
				210, 0.35, 0, 120, 45, 16, 0, new String[] {
				"tfc:rock/raw/basalt","ad_astra:moon_deepslate","tfc:rock/raw/gabbro","ad_astra:moon_stone","tfc:rock/raw/diorite","ad_astra:glacio_stone","tfc:rock/raw/dacite","tfc:rock/raw/rhyolite","tfc:rock/raw/andesite",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("blue_topaz", 35),new OreVeinInfoRecipe.WeightedBlock("topaz", 25),new OreVeinInfoRecipe.WeightedBlock("chalcocite", 25),new OreVeinInfoRecipe.WeightedBlock("bornite", 15),}),
			new OreVeinInfoRecipe("nether_anthracite", "minecraft:the_nether", 
				35, 0.8, 48, 127, 13, 4, 0, new String[] {
				"minecraft:deepslate",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("anthracite", 100),}),
			new OreVeinInfoRecipe("nether_apatite", "minecraft:the_nether", 
				220, 0.35, 48, 128, 39, 0, 0, new String[] {
				"tfc:rock/raw/schist","tfc:rock/raw/gneiss",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("apatite", 50),new OreVeinInfoRecipe.WeightedBlock("tricalcium_phosphate", 35),new OreVeinInfoRecipe.WeightedBlock("pyrochlore", 15),}),
			new OreVeinInfoRecipe("nether_basaltic_sands", "minecraft:the_nether", 
				160, 0.4, 48, 128, 48, 9, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/basalt",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("basaltic_mineral_sand", 35),new OreVeinInfoRecipe.WeightedBlock("granitic_mineral_sand", 25),new OreVeinInfoRecipe.WeightedBlock("fullers_earth", 25),new OreVeinInfoRecipe.WeightedBlock("gypsum", 15),}),
			new OreVeinInfoRecipe("nether_beryllium", "minecraft:the_nether", 
				250, 0.45, 32, 128, 0, 60, 12, new String[] {
				"minecraft:deepslate","minecraft:blackstone","tfc:rock/raw/basalt","minecraft:dripstone_block",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("beryllium", 33),new OreVeinInfoRecipe.WeightedBlock("emerald", 47),new OreVeinInfoRecipe.WeightedBlock("thorium", 0),new OreVeinInfoRecipe.WeightedBlock("rock_salt", 18),}),
			new OreVeinInfoRecipe("nether_cassiterite", "minecraft:the_nether", 
				170, 0.5, 32, 128, 45, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/gneiss","tfc:rock/raw/schist","minecraft:blackstone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("cassiterite", 40),new OreVeinInfoRecipe.WeightedBlock("tin", 60),}),
			new OreVeinInfoRecipe("nether_sheldonite", "minecraft:the_nether", 
				250, 0.4, 0, 128, 35, 0, 0, new String[] {
				"minecraft:deepslate","minecraft:blackstone","tfc:rock/raw/basalt","minecraft:dripstone_block",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("bornite", 41),new OreVeinInfoRecipe.WeightedBlock("cooperite", 29),new OreVeinInfoRecipe.WeightedBlock("platinum", 5),new OreVeinInfoRecipe.WeightedBlock("nickel", 23),}),
			new OreVeinInfoRecipe("nether_copper", "minecraft:the_nether", 
				170, 0.5, 32, 128, 45, 0, 0, new String[] {
				"minecraft:deepslate","minecraft:blackstone","tfc:rock/raw/basalt","minecraft:dripstone_block",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("chalcopyrite", 20),new OreVeinInfoRecipe.WeightedBlock("hematite", 5),new OreVeinInfoRecipe.WeightedBlock("pyrite", 10),new OreVeinInfoRecipe.WeightedBlock("copper", 65),}),
			new OreVeinInfoRecipe("nether_garnet", "minecraft:the_nether", 
				230, 0.35, 0, 128, 45, 8, 0, new String[] {
				"minecraft:deepslate","minecraft:blackstone","tfc:rock/raw/basalt","minecraft:dripstone_block",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("red_garnet", 9),new OreVeinInfoRecipe.WeightedBlock("yellow_garnet", 14),new OreVeinInfoRecipe.WeightedBlock("amethyst", 38),new OreVeinInfoRecipe.WeightedBlock("opal", 38),}),
			new OreVeinInfoRecipe("nether_garnet_tin", "minecraft:the_nether", 
				270, 0.35, 24, 128, 45, 0, 0, new String[] {
				"minecraft:deepslate","minecraft:blackstone","minecraft:dripstone_block","tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/schist","tfc:rock/raw/gneiss",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("cassiterite_sand", 35),new OreVeinInfoRecipe.WeightedBlock("garnet_sand", 25),new OreVeinInfoRecipe.WeightedBlock("asbestos", 25),new OreVeinInfoRecipe.WeightedBlock("diatomite", 15),}),
			new OreVeinInfoRecipe("nether_garnierite", "minecraft:the_nether", 
				160, 0.5, 16, 128, 45, 0, 0, new String[] {
				"tfc:rock/raw/gabbro","tfc:rock/raw/diorite","minecraft:blackstone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("garnierite", 23),new OreVeinInfoRecipe.WeightedBlock("nickel", 19),new OreVeinInfoRecipe.WeightedBlock("cobaltite", 19),new OreVeinInfoRecipe.WeightedBlock("pentlandite", 23),new OreVeinInfoRecipe.WeightedBlock("cobalt", 14),}),
			new OreVeinInfoRecipe("nether_goethite", "minecraft:the_nether", 
				240, 0.45, 0, 128, 37, 0, 0, new String[] {
				"minecraft:deepslate","minecraft:blackstone","tfc:rock/raw/basalt","minecraft:dripstone_block",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("goethite", 50),new OreVeinInfoRecipe.WeightedBlock("yellow_limonite", 15),new OreVeinInfoRecipe.WeightedBlock("hematite", 15),new OreVeinInfoRecipe.WeightedBlock("malachite", 20),}),
			new OreVeinInfoRecipe("nether_gold", "minecraft:the_nether", 
				260, 0.55, 0, 128, 37, 0, 0, new String[] {
				"tfc:rock/raw/gabbro","tfc:rock/raw/diorite","tfc:rock/raw/gneiss","tfc:rock/raw/granite","tfc:rock/raw/schist","minecraft:blackstone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("goethite", 5),new OreVeinInfoRecipe.WeightedBlock("yellow_limonite", 5),new OreVeinInfoRecipe.WeightedBlock("hematite", 15),new OreVeinInfoRecipe.WeightedBlock("gold", 75),}),
			new OreVeinInfoRecipe("nether_graphite", "minecraft:the_nether", 
				120, 0.35, 0, 128, 0, 60, 12, new String[] {
				"tfc:rock/raw/gabbro","tfc:rock/raw/gneiss","tfc:rock/raw/diorite","tfc:rock/raw/schist","tfc:rock/raw/granite","minecraft:blackstone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("graphite", 45),new OreVeinInfoRecipe.WeightedBlock("diamond", 40),new OreVeinInfoRecipe.WeightedBlock("coal", 15),}),
			new OreVeinInfoRecipe("nether_gypsum", "minecraft:the_nether", 
				180, 0.4, 32, 128, 40, 9, 0, new String[] {
				"minecraft:deepslate","minecraft:dripstone_block","minecraft:blackstone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("borax", 20),new OreVeinInfoRecipe.WeightedBlock("calcite", 30),new OreVeinInfoRecipe.WeightedBlock("fullers_earth", 15),new OreVeinInfoRecipe.WeightedBlock("gypsum", 35),}),
			new OreVeinInfoRecipe("nether_hematite", "minecraft:the_nether", 
				220, 0.45, 0, 128, 35, 0, 0, new String[] {
				"minecraft:deepslate","minecraft:blackstone","tfc:rock/raw/basalt","minecraft:dripstone_block",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("goethite", 25),new OreVeinInfoRecipe.WeightedBlock("yellow_limonite", 15),new OreVeinInfoRecipe.WeightedBlock("hematite", 35),new OreVeinInfoRecipe.WeightedBlock("gold", 5),new OreVeinInfoRecipe.WeightedBlock("ruby", 20),}),
			new OreVeinInfoRecipe("nether_lapis", "minecraft:the_nether", 
				220, 0.35, 32, 128, 40, 0, 0, new String[] {
				"minecraft:deepslate","minecraft:dripstone_block","minecraft:blackstone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("lazurite", 35),new OreVeinInfoRecipe.WeightedBlock("sodalite", 25),new OreVeinInfoRecipe.WeightedBlock("lapis", 25),new OreVeinInfoRecipe.WeightedBlock("calcite", 15),}),
			new OreVeinInfoRecipe("nether_lubricant", "minecraft:the_nether", 
				250, 0.35, 32, 128, 41, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/schist","tfc:rock/raw/gneiss","minecraft:blackstone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("soapstone", 30),new OreVeinInfoRecipe.WeightedBlock("talc", 20),new OreVeinInfoRecipe.WeightedBlock("glauconite_sand", 25),new OreVeinInfoRecipe.WeightedBlock("pentlandite", 15),new OreVeinInfoRecipe.WeightedBlock("trona", 10),}),
			new OreVeinInfoRecipe("nether_magnetite", "minecraft:the_nether", 
				205, 0.4, 0, 128, 39, 0, 0, new String[] {
				"minecraft:deepslate","minecraft:blackstone","tfc:rock/raw/basalt","minecraft:dripstone_block",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("magnetite", 20),new OreVeinInfoRecipe.WeightedBlock("vanadium_magnetite", 30),new OreVeinInfoRecipe.WeightedBlock("chromite", 10),new OreVeinInfoRecipe.WeightedBlock("gold", 30),new OreVeinInfoRecipe.WeightedBlock("sapphire", 10),}),
			new OreVeinInfoRecipe("nether_manganese", "minecraft:the_nether", 
				225, 0.4, 32, 128, 45, 0, 0, new String[] {
				"minecraft:deepslate","tfc:rock/raw/basalt","minecraft:blackstone","minecraft:dripstone_block",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("grossular", 37),new OreVeinInfoRecipe.WeightedBlock("spessartine", 25),new OreVeinInfoRecipe.WeightedBlock("pyrolusite", 25),new OreVeinInfoRecipe.WeightedBlock("tantalite", 12),}),
			new OreVeinInfoRecipe("nether_mica", "minecraft:the_nether", 
				220, 0.35, 32, 128, 41, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/schist","tfc:rock/raw/gneiss","minecraft:blackstone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("kyanite", 46),new OreVeinInfoRecipe.WeightedBlock("mica", 33),new OreVeinInfoRecipe.WeightedBlock("pollucite", 20),}),
			new OreVeinInfoRecipe("nether_molybdenum", "minecraft:the_nether", 
				245, 0.55, 0, 128, 31, 0, 0, new String[] {
				"tfc:rock/raw/gneiss","tfc:rock/raw/schist","tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","minecraft:blackstone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("wulfenite", 42),new OreVeinInfoRecipe.WeightedBlock("molybdenite", 31),new OreVeinInfoRecipe.WeightedBlock("powellite", 10),new OreVeinInfoRecipe.WeightedBlock("nickel", 15),}),
			new OreVeinInfoRecipe("nether_monazite", "minecraft:the_nether", 
				245, 0.35, 24, 128, 45, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/schist","tfc:rock/raw/gneiss","minecraft:blackstone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("bastnasite", 50),new OreVeinInfoRecipe.WeightedBlock("monazite", 25),new OreVeinInfoRecipe.WeightedBlock("neodymium", 25),}),
			new OreVeinInfoRecipe("nether_naquadah", "minecraft:the_nether", 
				250, 0.3, 0, 38, 32, 0, 0, new String[] {
				"minecraft:blackstone","tfc:rock/raw/basalt",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("naquadah", 100),}),
			new OreVeinInfoRecipe("nether_olivine", "minecraft:the_nether", 
				250, 0.35, 24, 128, 31, 0, 0, new String[] {
				"minecraft:deepslate","tfc:rock/raw/basalt","minecraft:blackstone","minecraft:dripstone_block",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("bentonite", 35),new OreVeinInfoRecipe.WeightedBlock("magnesite", 25),new OreVeinInfoRecipe.WeightedBlock("olivine", 25),new OreVeinInfoRecipe.WeightedBlock("glauconite_sand", 15),}),
			new OreVeinInfoRecipe("nether_pitchblende", "minecraft:the_nether", 
				220, 0.55, 0, 128, 29, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/schist","tfc:rock/raw/gneiss","minecraft:blackstone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("pitchblende", 62),new OreVeinInfoRecipe.WeightedBlock("uraninite", 25),new OreVeinInfoRecipe.WeightedBlock("wulfenite", 12),}),
			new OreVeinInfoRecipe("nether_quartz", "minecraft:the_nether", 
				150, 0.4, 0, 128, 45, 0, 0, new String[] {
				"minecraft:deepslate","minecraft:blackstone","tfc:rock/raw/basalt","minecraft:dripstone_block","tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("quartzite", 25),new OreVeinInfoRecipe.WeightedBlock("nether_quartz", 54),new OreVeinInfoRecipe.WeightedBlock("barite", 20),}),
			new OreVeinInfoRecipe("nether_redstone", "minecraft:the_nether", 
				160, 0.5, 0, 128, 45, 0, 0, new String[] {
				"tfc:rock/raw/granite","minecraft:blackstone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("redstone", 45),new OreVeinInfoRecipe.WeightedBlock("ruby", 35),new OreVeinInfoRecipe.WeightedBlock("cinnabar", 20),}),
			new OreVeinInfoRecipe("nether_saltpeter", "minecraft:the_nether", 
				210, 0.4, 32, 128, 50, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/schist","tfc:rock/raw/gneiss","minecraft:blackstone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("saltpeter", 35),new OreVeinInfoRecipe.WeightedBlock("diatomite", 25),new OreVeinInfoRecipe.WeightedBlock("electrotine", 25),new OreVeinInfoRecipe.WeightedBlock("alunite", 15),}),
			new OreVeinInfoRecipe("nether_sapphire", "minecraft:the_nether", 
				180, 0.45, 0, 128, 33, 8, 0, new String[] {
				"tfc:rock/raw/gabbro","tfc:rock/raw/granite","tfc:rock/raw/gneiss","tfc:rock/raw/diorite","tfc:rock/raw/schist","minecraft:blackstone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("almandine", 38),new OreVeinInfoRecipe.WeightedBlock("pyrope", 27),new OreVeinInfoRecipe.WeightedBlock("sapphire", 16),new OreVeinInfoRecipe.WeightedBlock("green_sapphire", 16),}),
			new OreVeinInfoRecipe("nether_scheelite", "minecraft:the_nether", 
				180, 0.45, 0, 128, 25, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/diorite","tfc:rock/raw/gabbro","tfc:rock/raw/gneiss","tfc:rock/raw/schist","minecraft:blackstone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("scheelite", 45),new OreVeinInfoRecipe.WeightedBlock("tungstate", 35),new OreVeinInfoRecipe.WeightedBlock("lithium", 20),}),
			new OreVeinInfoRecipe("nether_silver", "minecraft:the_nether", 
				160, 0.5, 24, 128, 45, 0, 0, new String[] {
				"tfc:rock/raw/granite","tfc:rock/raw/gneiss","minecraft:blackstone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("galena", 30),new OreVeinInfoRecipe.WeightedBlock("silver", 35),new OreVeinInfoRecipe.WeightedBlock("lead", 35),}),
			new OreVeinInfoRecipe("nether_sphalerite", "minecraft:the_nether", 
				170, 0.5, 32, 128, 45, 0, 0, new String[] {
				"minecraft:deepslate","tfc:rock/raw/basalt","minecraft:blackstone","minecraft:dripstone_block",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("sulfur", 35),new OreVeinInfoRecipe.WeightedBlock("sphalerite", 40),new OreVeinInfoRecipe.WeightedBlock("pyrite", 25),}),
			new OreVeinInfoRecipe("nether_sulfur", "minecraft:the_nether", 
				165, 0.3, 0, 128, 50, 0, 0, new String[] {
				"tfc:rock/raw/diorite","tfc:rock/raw/basalt","minecraft:blackstone","tfc:rock/raw/schist",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("sulfur", 50),new OreVeinInfoRecipe.WeightedBlock("pyrite", 35),new OreVeinInfoRecipe.WeightedBlock("sphalerite", 15),}),
			new OreVeinInfoRecipe("nether_sylvite", "minecraft:the_nether", 
				75, 0.6, 0, 64, 17, 0, 0, new String[] {
				"minecraft:blackstone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("sylvite", 100),}),
			new OreVeinInfoRecipe("nether_tetrahedrite", "minecraft:the_nether", 
				170, 0.5, 32, 128, 45, 0, 0, new String[] {
				"minecraft:deepslate","minecraft:dripstone_block","tfc:rock/raw/schist","tfc:rock/raw/gneiss","minecraft:blackstone",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("tetrahedrite", 50),new OreVeinInfoRecipe.WeightedBlock("copper", 30),new OreVeinInfoRecipe.WeightedBlock("stibnite", 20),}),
			new OreVeinInfoRecipe("nether_topaz", "minecraft:the_nether", 
				180, 0.4, 0, 128, 33, 7, 0, new String[] {
				"minecraft:blackstone","minecraft:deepslate","tfc:rock/raw/basalt","minecraft:dripstone_block",}, new OreVeinInfoRecipe.WeightedBlock[] {
				new OreVeinInfoRecipe.WeightedBlock("blue_topaz", 35),new OreVeinInfoRecipe.WeightedBlock("topaz", 25),new OreVeinInfoRecipe.WeightedBlock("chalcocite", 25),new OreVeinInfoRecipe.WeightedBlock("bornite", 15),}),
	};
}
